# Generated by Django 6.1 on 2026-08-22 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_accesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use international format, for example +5511999999999.",
                        regex="^\\+[1-9]\\d{7,14}$",
                    )
                ],
            ),
        ),
    ]
