# Generated by Django 6.1 on 2026-08-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_whatsapp_number"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("whatsapp_number", ""), _negated=True),
                fields=("whatsapp_number",),
                name="accounts_user_whatsapp_nonempty_unique",
            ),
        ),
    ]
