# Generated by Django 6.1 on 2026-08-22 19:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("publisher", models.CharField(max_length=255)),
                ("edition", models.CharField(max_length=100)),
                ("publication_year", models.PositiveSmallIntegerField()),
                ("category", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("cover", models.FileField(upload_to="covers/")),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "author", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.FileField(upload_to="books/")),
                ("alt_text", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="catalog.booktitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("internal_code", models.CharField(max_length=100, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("loaned", "Loaned"),
                            ("lost", "Lost"),
                            ("discarded", "Discarded"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "condition_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies",
                        to="catalog.booktitle",
                    ),
                ),
            ],
            options={
                "ordering": ["-condition_rating", "id"],
            },
        ),
        migrations.AddField(
            model_name="booktitle",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="titles", to="catalog.tag"),
        ),
        migrations.AddIndex(
            model_name="booktitle",
            index=models.Index(fields=["name"], name="catalog_boo_name_8b5b00_idx"),
        ),
        migrations.AddIndex(
            model_name="booktitle",
            index=models.Index(fields=["author"], name="catalog_boo_author_b62bd9_idx"),
        ),
    ]
