# Generated by Django 6.1 on 2026-08-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktitle",
            name="metadata_source_url",
            field=models.URLField(blank=True),
        ),
    ]
