# Generated by Django 6.1 on 2026-08-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("calculus", "Calculus"),
                            ("ocean", "Ocean"),
                            ("wine", "Wine"),
                            ("slate", "Slate"),
                            ("indigo", "Indigo"),
                            ("aqua", "Aqua Glass"),
                        ],
                        default="calculus",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
