# Generated by Django 6.1 on 2026-08-22 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("is_open", models.BooleanField(default=False)),
                ("label", models.CharField(max_length=160)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="RegularOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="CancellationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("administrative", models.BooleanField(default=False)),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("effective_from", models.DateTimeField(auto_now_add=True)),
                ("min_loan_days", models.PositiveSmallIntegerField(default=3)),
                ("max_loan_days", models.PositiveSmallIntegerField(default=15)),
                ("simultaneous_loan_limit", models.PositiveSmallIntegerField(default=3)),
                ("pickup_tolerance_days", models.PositiveSmallIntegerField(default=1)),
                ("late_penalty_days", models.PositiveSmallIntegerField(default=7)),
                ("cancellation_limit", models.PositiveSmallIntegerField(default=3)),
                ("cancellation_window_days", models.PositiveSmallIntegerField(default=30)),
                ("globally_suspended", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_loan_days__gte", models.F("min_loan_days"))),
                        name="policy_max_days_gte_min_days",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReservationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="catalog.booktitle",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "copy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="catalog.bookcopy",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="circulation.policyversion"
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="catalog.booktitle",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="reservation_end_gte_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("copy__isnull", True), ("state", "waiting")),
                            models.Q(("state", "waiting"), _negated=True),
                            _connector="OR",
                        ),
                        name="waiting_reservation_has_no_copy",
                    ),
                ],
            },
        ),
    ]
