# Generated by Django 6.1 on 2026-08-22 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circulation", "0002_penalty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="exclusivity_lost_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservationrequest",
            name="reservation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_request",
                to="circulation.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("needs_reschedule", "Needs reschedule"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InternalNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        choices=[("accepted", "Accepted"), ("declined", "Declined")],
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("checked_out_at", models.DateTimeField()),
                ("due_date", models.DateField()),
                ("returned_on", models.DateField(blank=True, null=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan",
                        to="circulation.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_out_at", "-id"],
            },
        ),
    ]
