# Generated by Django 6.1 on 2026-08-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circulation", "0003_reservation_exclusivity_lost_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="blocks_new",
            field=models.BooleanField(default=True),
        ),
    ]
